namespace $ {

	export const $bun_alh_game_elements: Array< $bun_alh_game_element > = [

		{ id: 'water', name: 'Вода' },
        { id: 'fire', name: 'Огонь' },
        { id: 'air',  name: 'Воздух' },
        { id: 'earth',  name: 'Земля' },
        { id: 'dust', name: 'Пыль' },
        { id: 'energy', name: 'Энергия' },
        { id: 'land', name: 'Территория' },
        { id: 'lava', name: 'Лава' },
        { id: 'mist', name: 'Туман' },
        { id: 'mud', name: 'Грязь' },
        { id: 'pressure', name: 'Давление' },
        { id: 'puddle', name: 'Лужа' },
        { id: 'smoke', name: 'Дым' },
        { id: 'steam', name: 'Пар' },
        { id: 'brick', name: 'Кирпич' },
        { id: 'continent', name: 'Континент' },
        { id: 'earthquake', name: 'Землетрясение' },
        { id: 'eruption', name: 'Извержение' },
        { id: 'geyser', name: 'Гейзер' },
        { id: 'granite', name: 'Гранит' },
        { id: 'gunpowder', name: 'Порох' },
        { id: 'heat', name: 'Жара' },
        { id: 'obsidian', name: 'Обсидиан' },
        { id: 'pond', name: 'Пруд' },
        { id: 'stone', name: 'Камень' },
        { id: 'volcano', name: 'Вулкан' },
        { id: 'wind', name: 'Ветер' },
        { id: 'chimney', name: 'Труба' },
        { id: 'clay', name: 'Глина' },
        { id: 'explosion', name: 'Взрыв' },
        { id: 'lake', name: 'Озеро' },
        { id: 'metal', name: 'Металл' },
        { id: 'mountain', name: 'Гора' },
        { id: 'planet', name: 'Планета' },
        { id: 'plasma', name: 'Плазма' },
        { id: 'sand', name: 'Песок' },
        { id: 'tornado', name: 'Торнадо' },
        { id: 'wall', name: 'Стена' },
        { id: 'warmth', name: 'Тепло' },
        { id: 'atmosphere', name: 'Атмосфера' },
        { id: 'atomic_bomb', name: 'Атомная бомба' },
        { id: 'avalanche', name: 'Лавина' },
        { id: 'beach', name: 'Пляж' },
        { id: 'blade', name: 'Лезвие' },
        { id: 'boiler', name: 'Бойлер' },
        { id: 'bullet', name: 'Пуля' },
        { id: 'desert', name: 'Пустыня' },
        { id: 'dune', name: 'Дюна' },
        { id: 'firewall', name: 'Противопожарная перегородка' },
        { id: 'glass', name: 'Стекло' },
        { id: 'gold', name: 'Золото' },
        { id: 'sun', name: 'Солнце' },
        { id: 'cloud', name: 'Облако' },
        { id: 'sky', name: 'Небо' },
		{ id: 'sea', name: 'Море' },

	]

}
